Repository Next-Gene/primecare, pull requests merged in 2025-04, with the labels that each got.

#14 Refactor add xml docs
  PrimeCare.Application/Dtos/ProductBrand/CreateProductBrandDto.cs
  PrimeCare.Application/Dtos/ProductBrand/ProductBrandDto.cs
  PrimeCare.Application/Dtos/ProductType/CreateProductTypeDto.cs
  PrimeCare.Application/Dtos/ProductType/ProductTypeDto.cs
  PrimeCare.Application/Dtos/ServiceResponse.cs
  PrimeCare.Application/Errors/ApiException.cs
  PrimeCare.Application/Errors/ApiResponse.cs
  PrimeCare.Application/Helpers/MappingProfiles.cs
  PrimeCare.Application/Helpers/ProductUrlResolver.cs
  PrimeCare.Application/Services/Implementations/ProductBrandService.cs
  PrimeCare.Application/Services/Implementations/ProductService.cs
  PrimeCare.Application/Services/Implementations/ProductTypeService.cs
  PrimeCare.Application/Services/Interfaces/IProductTypeService.cs
  PrimeCare.Infrastructure/Repositories/GenericRepository.cs
  PrimeCare.Infrastructure/ServiceContainer.cs
Labels: documentation, refactor

#15 Configure validation errors
  PrimeCare.Api/Program.cs
  PrimeCare.Application/Errors/ApiValidationErrorResponse.cs
Labels: bug, documentation, enhancement

#16 Add error handling route and API explorer settings
  PrimeCare.Api/Controllers/ErrorController.cs
Labels: bug

#17 Handel api responses
  PrimeCare.Api/Controllers/ProductBrandController.cs
  PrimeCare.Api/Controllers/ProductController.cs
  PrimeCare.Api/Controllers/ProductTypeController.cs
Labels: bug, refactor

#18 Refactor and improve documentation for service classes (ProductTypeSe…
  PrimeCare.Application/Services/Implementations/ProductBrandService.cs
  PrimeCare.Application/Services/Implementations/ProductService.cs
  PrimeCare.Application/Services/Implementations/ProductTypeService.cs
Labels: documentation, refactor

#25 Refactor Category entity and migration files
  PrimeCare.Core/Entities/Category.cs
  PrimeCare.Infrastructure/Data/Configuration/CategoryConfiguration.cs
  PrimeCare.Infrastructure/Migrations/20250418141040_Initial.Designer.cs
  PrimeCare.Infrastructure/Migrations/20250418141040_Initial.cs
  PrimeCare.Infrastructure/Migrations/PrimeCareContextModelSnapshot.cs
Labels: enhancement

#26 Add Category mapping and URL resolver
  PrimeCare.Api/wwwroot/images/category/boards.png
  PrimeCare.Application/Helpers/CategoryUrlResolver.cs
  PrimeCare.Application/Helpers/MappingProfiles.cs
  PrimeCare.Infrastructure/Data/SeedData/categories.json
Labels: enhancement

#27 Add product management endpoints and DTO updates
  PrimeCare.Api/Controllers/ProductController.cs
  PrimeCare.Application/Dtos/Product/BaseProductDto.cs
  PrimeCare.Application/Dtos/Product/CreateProductDto.cs
  PrimeCare.Application/Dtos/Product/ProductDto.cs
  PrimeCare.Application/Dtos/Product/UpdateProductDto.cs
  PrimeCare.Application/Helpers/MappingProfiles.cs
  PrimeCare.Application/Services/Implementations/ProductService.cs
  PrimeCare.Application/Services/Interfaces/IProductService.cs
Labels: enhancement, refactor

#28 Update category handling to use UpdateCategoryDto
  PrimeCare.Api/Controllers/CategoryController.cs
  PrimeCare.Application/Services/Implementations/CategoryService.cs
  PrimeCare.Application/Services/Interfaces/ICategoryService.cs
Labels: refactor

#31 move swagger deco to extensions file
  PrimeCare.Api/Extensions/ApplicationServicesExtensions.cs
  PrimeCare.Api/Extensions/SwaggerServiceExtension.cs
  PrimeCare.Api/Program.cs
Labels: enhancement, refactor

#33 Update README.md
  README.md
Labels: enhancement

#38 add support for ordering via OrderBy and OrderByDescending
  src/PrimeCare.Core/Specifications/BaseSpecification.cs
  src/PrimeCare.Core/Specifications/ISpecification.cs
  src/PrimeCare.Infrastructure/Data/SpecificationEvaluator.cs
Labels: enhancement

#39 refacotre photo services and logic
  src/PrimeCare.Api/Controllers/CategoryController.cs
  src/PrimeCare.Api/Controllers/ProductController.cs
  src/PrimeCare.Api/Extensions/ApplicationServicesExtensions.cs
  src/PrimeCare.Api/Program.cs
  src/PrimeCare.Api/appsettings.Development.json
  src/PrimeCare.Application/Helpers/CloudinarySettings.cs
  src/PrimeCare.Application/Helpers/MappingProfiles.cs
  src/PrimeCare.Application/ServiceContainer.cs
  src/PrimeCare.Application/Services/Implementations/CategoryService.cs
  src/PrimeCare.Application/Services/Implementations/PhotoService.cs
  src/PrimeCare.Application/Services/Implementations/ProductService.cs
  src/PrimeCare.Application/Services/Interfaces/ICategoryService.cs
  src/PrimeCare.Application/Services/Interfaces/IPhotosService.cs
  src/PrimeCare.Application/Services/Interfaces/IPhotosServies.cs
  src/PrimeCare.Core/Entities/Category.cs
  src/PrimeCare.Core/Entities/CategoryPhoto.cs
  src/PrimeCare.Core/Entities/Product.cs
  src/PrimeCare.Core/Entities/ProductPhoto.cs
  src/PrimeCare.Core/Entities/ProductPhotos.cs
  src/PrimeCare.Core/Interfaces/IGenericRepository.cs
  src/PrimeCare.Infrastructure/Data/PrimeCareContext.cs
  src/PrimeCare.Infrastructure/Migrations/20250425233731_Initial.Designer.cs
  src/PrimeCare.Infrastructure/Migrations/20250425233731_Initial.cs
  src/PrimeCare.Infrastructure/Migrations/PrimeCareContextModelSnapshot.cs
  src/PrimeCare.Infrastructure/Repositories/GenericRepository.cs
  src/PrimeCare.Infrastructure/ServiceContainer.cs
  src/PrimeCare.Shared/Dtos/Categories/CategoryDto.cs
  src/PrimeCare.Shared/Dtos/Photos/CategoryPhotoDto.cs
  src/PrimeCare.Shared/Dtos/Photos/ProductPhotoDto.cs
  src/PrimeCare.Shared/Dtos/Photos/ProductPhotosDto.cs
  src/PrimeCare.Shared/Dtos/Products/BaseProductDto.cs
  src/PrimeCare.Shared/Dtos/Products/CreateProductDto.cs
  src/PrimeCare.Shared/Dtos/Products/ProductDto.cs
  src/PrimeCare.Shared/Dtos/Products/UpdateProductDto.cs
Labels: bug, refactor

#40 Enhancement/category photo
  src/PrimeCare.Api/Controllers/CategoryController.cs
  src/PrimeCare.Api/Controllers/ProductController.cs
  src/PrimeCare.Application/Helpers/MappingProfiles.cs
  src/PrimeCare.Core/Entities/Category.cs
  src/PrimeCare.Core/Entities/CategoryPhoto.cs
  src/PrimeCare.Core/Entities/Product.cs
  src/PrimeCare.Core/Specifications/CategoryPhotoSepcification.cs
  src/PrimeCare.Infrastructure/Migrations/20250426122544_Initail.Designer.cs
  src/PrimeCare.Infrastructure/Migrations/20250426122544_Initail.cs
  src/PrimeCare.Infrastructure/Migrations/PrimeCareContextModelSnapshot.cs
  src/PrimeCare.Shared/Dtos/Categories/CreateCategoryDto.cs
  src/PrimeCare.Shared/Dtos/Photos/CategoryPhotoDto.cs
  src/PrimeCare.Shared/Dtos/Products/CreateProductDto.cs
  src/PrimeCare.Shared/Dtos/Products/ProductDto.cs
  src/PrimeCare.Shared/Dtos/Products/UpdateProductDto.cs
Labels: bug, enhancement

#41 Refactor DI registration to use open generic for IGenericRepository
  src/PrimeCare.Api/Extensions/ApplicationServicesExtensions.cs
  src/PrimeCare.Infrastructure/ServiceContainer.cs
Labels: enhancement, refactor
